name: Go Test

on:
  push:
    paths:
      - 'go/**'
      - '.github/workflows/ci-go.yaml'
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/ci-go.yaml'

jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run tests with coverage report output
        run: go test -coverprofile=coverage.out
        working-directory: go/
      - uses: k1LoW/octocov-action@v1.3.0
      # add commit status to octocov link using github-script
      - name: Add commit status to octocov link
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // get artifact lists of the workflow
            const artifacts = await github.actions.listArtifactsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            // get the artifact id of the octocov report
            const octocovArtifact = artifacts.data.artifacts.find(artifact => artifact.name === 'report.json');
            if(!octocovArtifact) {
              return;
            }
            // create a commit status with the octocov report link
            const artifactId = octocovArtifact.id;
            const artifactDownloadUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifactId}`;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              target_url: artifactDownloadUrl,
              description: 'Octocov report',
              context: 'octocov'
            });
